### ISSUE TITLE
Why .Net v4.7.1?

### ISSUE THREAD

**Issue by Digitalroot** [WhiteFang5/PoE-Asset-Updater#2]
Why the need for 4.7.1 and not 4.8?

**Comment by WhiteFang5** [comment]
There is no specific reason, besides the fact that I prefer to coee in c# 7.3 or later. Do you have a suggestion for a change in .Net version? Or was this rather a question of curiosity?

**Comment by Digitalroot** [comment]
It was a question around if there was something that limited it to 4.7.1 vs 4.7.2 or 4.8

**Comment by Digitalroot** [comment]
I just switched it to 4.8 and so far so good.

**Comment by Digitalroot** [comment]
I just looked into porting it to core. It won't go to core unless libggpk is ported to core too.

**Comment by WhiteFang5** [comment]
Libggpk is opensource, so it should be possible by forking that project, porting it and putting the release ddls in this project

**Comment by WhiteFang5** [comment]
I'll be closing this issue as I've actually updated the project to .NET Core 3.1
